-- Re-runnable seed script for DB testing.
-- It creates 1 dedicated test plan, 50 planned activities, and 100 realized rows.
-- Safe to run multiple times: it only deletes/recreates rows generated by this script.
--
-- Usage:
--   mysql -u root csr_db < backend/migrations/seed_test_activities.sql
--
-- Defaults:
--   - first site in `sites`
--   - first user in `users`
--   - year 2099

SET @seed_year := 2099;
SET @planned_count := 50;
SET @realized_count := 100;
SET @seed_prefix := 'SEED-PA-';
SET @seed_pattern := CONCAT(CONVERT(@seed_prefix USING utf8mb4) COLLATE utf8mb4_unicode_ci, '%');

SET @site_id := (SELECT id FROM sites ORDER BY code, name LIMIT 1);
SET @user_id := (SELECT id FROM users ORDER BY email LIMIT 1);
SET @category_count := (SELECT COUNT(*) FROM categories);

START TRANSACTION;

INSERT INTO csr_plans (
    id,
    site_id,
    year,
    validation_mode,
    status,
    allocated_budget,
    total_hc,
    created_by,
    created_at,
    updated_at
)
SELECT
    UUID(),
    @site_id,
    @seed_year,
    '101',
    'DRAFT',
    250000.00,
    1200,
    @user_id,
    NOW(),
    NOW()
FROM dual
WHERE @site_id IS NOT NULL
  AND @user_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM csr_plans p
      WHERE p.site_id = @site_id
        AND p.year = @seed_year
  );

SET @plan_id := (
    SELECT id
    FROM csr_plans
    WHERE site_id = @site_id
      AND year = @seed_year
    LIMIT 1
);

DROP TEMPORARY TABLE IF EXISTS tmp_generated_activities;
CREATE TEMPORARY TABLE tmp_generated_activities AS
SELECT id
FROM planned_activity
WHERE 1 = 0;

DELETE ro
FROM csr_completed_objectives ro
JOIN planned_activity pa ON pa.id = ro.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE ao
FROM csr_objectives ao
JOIN planned_activity pa ON pa.id = ao.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE atc
FROM csr_attachments atc
JOIN planned_activity pa ON pa.id = atc.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE ra
FROM realized_activity ra
JOIN planned_activity pa ON pa.id = ra.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DROP TEMPORARY TABLE IF EXISTS tmp_categories;
CREATE TEMPORARY TABLE tmp_categories AS
SELECT
    id,
    ROW_NUMBER() OVER (ORDER BY name, id) AS rn
FROM categories;

DROP TEMPORARY TABLE IF EXISTS tmp_seq_planned;
CREATE TEMPORARY TABLE tmp_seq_planned (
    n INT PRIMARY KEY
);

INSERT INTO tmp_seq_planned (n)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < @planned_count
)
SELECT n
FROM seq;

INSERT INTO planned_activity (
    id,
    plan_id,
    category_id,
    external_partner_id,
    activity_number,
    title,
    organization,
    contract_type,
    description,
    collaboration_nature,
    periodicity,
    planned_budget,
    action_impact_target,
    action_impact_unit,
    action_impact_duration,
    employees_planned,
    start_year,
    edition,
    organizer,
    status,
    created_by,
    created_at,
    updated_at
)
SELECT
    UUID(),
    @plan_id,
    c.id,
    NULL,
    CONCAT(@seed_prefix, LPAD(s.n, 3, '0')),
    CONCAT('Seed Planned Activity ', s.n),
    IF(MOD(s.n, 2) = 0, 'Internal', 'External'),
    IF(MOD(s.n, 2) = 0, 'One shot', 'Successive performance'),
    CONCAT('Generated test planned activity #', s.n, ' for database validation.'),
    ELT((MOD(s.n - 1, 4) + 1), 'PARTNERSHIP', 'SPONSORSHIP', 'CHARITY_DONATION', 'OTHERS'),
    ELT((MOD(s.n - 1, 4) + 1), 'Monthly', 'Quarterly', 'Annual', 'One-time'),
    1000 + (s.n * 125),
    10 + s.n,
    ELT((MOD(s.n - 1, 4) + 1), 'people', 'trees', 'hours', 'kits'),
    ELT((MOD(s.n - 1, 3) + 1), '1 month', '6 months', '1 year'),
    5 + MOD(s.n, 25),
    @seed_year,
    1 + MOD(s.n - 1, 5),
    ELT((MOD(s.n - 1, 4) + 1), 'HR', 'Operations', 'QHSE', 'CSR Team'),
    'DRAFT',
    @user_id,
    NOW(),
    NOW()
FROM tmp_seq_planned s
JOIN tmp_categories c
  ON c.rn = MOD(s.n - 1, @category_count) + 1;

DROP TEMPORARY TABLE IF EXISTS tmp_generated_activities;
CREATE TEMPORARY TABLE tmp_generated_activities AS
SELECT
    id,
    ROW_NUMBER() OVER (ORDER BY activity_number) AS rn
FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

INSERT INTO csr_objectives (
    id,
    activity_id,
    objective,
    created_at
)
SELECT
    UUID(),
    ga.id,
    CONCAT('Announced objective ', obj.obj_no, ' for activity ', LPAD(ga.rn, 3, '0')),
    NOW()
FROM tmp_generated_activities ga
JOIN (
    SELECT 1 AS obj_no
    UNION ALL
    SELECT 2
) obj;

INSERT INTO csr_completed_objectives (
    id,
    activity_id,
    objective,
    achieved,
    created_at
)
SELECT
    UUID(),
    ga.id,
    CONCAT('Completed objective 1 for activity ', LPAD(ga.rn, 3, '0')),
    TRUE,
    NOW()
FROM tmp_generated_activities ga;

DROP TEMPORARY TABLE IF EXISTS tmp_seq_realized;
CREATE TEMPORARY TABLE tmp_seq_realized (
    n INT PRIMARY KEY
);

INSERT INTO tmp_seq_realized (n)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < @realized_count
)
SELECT n
FROM seq;

INSERT INTO realized_activity (
    id,
    activity_id,
    participants,
    corporate_image_improved,
    incidents_number,
    contact_department,
    realized_budget,
    action_impact_actual,
    action_impact_unit,
    is_off_plan,
    off_plan_validation_mode,
    off_plan_validation_step,
    realization_date,
    comment,
    contact_name,
    contact_email,
    created_by,
    created_at,
    updated_at,
    status
)
SELECT
    UUID(),
    ga.id,
    8 + MOD(sr.n, 40),
    IF(MOD(sr.n, 5) = 0, FALSE, TRUE),
    MOD(sr.n, 4),
    ELT((MOD(sr.n - 1, 4) + 1), 'HR', 'Operations', 'QHSE', 'CSR Team'),
    700 + (sr.n * 45),
    5 + sr.n,
    ELT((MOD(sr.n - 1, 4) + 1), 'people', 'trees', 'hours', 'kits'),
    FALSE,
    NULL,
    NULL,
    DATE_ADD(MAKEDATE(@seed_year, 1), INTERVAL MOD(sr.n * 7, 330) DAY),
    CONCAT('Generated test realization #', sr.n),
    CONCAT('Seed Contact ', sr.n),
    CONCAT('seed+', sr.n, '@example.com'),
    @user_id,
    NOW(),
    NOW(),
    'DRAFT'
FROM tmp_seq_realized sr
JOIN tmp_generated_activities ga
  ON ga.rn = MOD(sr.n - 1, @planned_count) + 1;

COMMIT;

SELECT 'seed_test_activities.sql completed' AS message;
SELECT @site_id AS site_id, @plan_id AS plan_id, @seed_year AS plan_year;
SELECT COUNT(*) AS planned_seeded
FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;
SELECT COUNT(*) AS realized_seeded
FROM realized_activity ra
JOIN planned_activity pa ON pa.id = ra.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;
