-- Re-runnable seed script for DB testing (manual only — not run by init_db.py).
-- It creates 1 dedicated test plan, 50 planned activities, and 100 realized rows.
-- The full annual plan is inserted in DRAFT (plan, lines, reports), then whole-plan validation
-- (plan VALIDATED + validated_at, lines and reports VALIDATED) before KPI rows are built, so
-- activity_kpis.lifecycle_status follows planned vs realized data.
-- Safe to run multiple times: it only deletes/recreates rows generated by this script.
--
-- Usage:
--   mysql -u root csr_db < backend/migrations/seed_test_activities.sql
--
-- Defaults:
--   - first site in `sites`
--   - first user in `users`
--   - plan year below (@seed_year)

-- Adjust for manual runs; init_db.py does not execute this file.
SET @seed_year := 2038;
SET @planned_count := 50;
SET @realized_count := 100;
SET @seed_prefix := 'SEED-PA-';
SET @seed_pattern := CONCAT(CONVERT(@seed_prefix USING utf8mb4) COLLATE utf8mb4_unicode_ci, '%');

SET @site_id := (SELECT id FROM sites ORDER BY code, name LIMIT 1);
SET @user_id := (SELECT id FROM users ORDER BY email LIMIT 1);
SET @category_count := (SELECT COUNT(*) FROM categories);

START TRANSACTION;

INSERT INTO csr_plans (
    id,
    site_id,
    year,
    validation_mode,
    status,
    allocated_budget,
    total_hc,
    created_by,
    created_at,
    updated_at
)
SELECT
    UUID(),
    @site_id,
    @seed_year,
    '101',
    'DRAFT',
    250000.00,
    1200,
    @user_id,
    NOW(),
    NOW()
FROM dual
WHERE @site_id IS NOT NULL
  AND @user_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM csr_plans p
      WHERE p.site_id = @site_id
        AND p.year = @seed_year
  );

SET @plan_id := (
    SELECT id
    FROM csr_plans
    WHERE site_id = @site_id
      AND year = @seed_year
    LIMIT 1
);

DROP TEMPORARY TABLE IF EXISTS tmp_generated_activities;
CREATE TEMPORARY TABLE tmp_generated_activities AS
SELECT id
FROM planned_activity
WHERE 1 = 0;

DELETE ro
FROM csr_completed_objectives ro
JOIN planned_activity pa ON pa.id = ro.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE ao
FROM csr_objectives ao
JOIN planned_activity pa ON pa.id = ao.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE atc
FROM csr_attachments atc
JOIN planned_activity pa ON pa.id = atc.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE ra
FROM realized_activity ra
JOIN planned_activity pa ON pa.id = ra.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE ak
FROM activity_kpis ak
JOIN planned_activity pa ON pa.id = ak.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DELETE FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

DROP TEMPORARY TABLE IF EXISTS tmp_categories;
CREATE TEMPORARY TABLE tmp_categories AS
SELECT
    id,
    ROW_NUMBER() OVER (ORDER BY name, id) AS rn
FROM categories;

DROP TEMPORARY TABLE IF EXISTS tmp_seq_planned;
CREATE TEMPORARY TABLE tmp_seq_planned (
    n INT PRIMARY KEY
);

INSERT INTO tmp_seq_planned (n)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < @planned_count
)
SELECT n
FROM seq;

DROP TEMPORARY TABLE IF EXISTS tmp_partner_names;
CREATE TEMPORARY TABLE tmp_partner_names AS
SELECT
    s.n AS n,
    CONCAT(
        ELT((MOD(s.n - 1, 5) + 1), 'Atlas Partner ', 'Green Partner ', 'Future Partner ', 'Care Partner ', 'Impact Partner '),
        LPAD((MOD((s.n * 3), 23) + 1), 2, '0')
    ) AS partner_name
FROM tmp_seq_planned s;

INSERT INTO external_partners (
    id, name, type, contact_person, email, phone, is_active, created_at, updated_at
)
SELECT
    UUID(),
    t.partner_name,
    'OTHER',
    CONCAT('Seed Partner Contact ', t.n),
    CONCAT('seed.partner.', t.n, '@example.com'),
    CONCAT('+212600', LPAD(t.n, 4, '0')),
    TRUE,
    NOW(),
    NOW()
FROM tmp_partner_names t
LEFT JOIN external_partners ep
    ON ep.name COLLATE utf8mb4_unicode_ci = t.partner_name COLLATE utf8mb4_unicode_ci
WHERE ep.id IS NULL;

INSERT INTO planned_activity (
    id,
    plan_id,
    category_id,
    external_partner_id,
    activity_number,
    title,
    organization,
    contract_type,
    description,
    collaboration_nature,
    periodicity,
    planned_budget,
    action_impact_target,
    action_impact_unit,
    action_impact_duration,
    employees_planned,
    start_year,
    edition,
    organizer,
    status,
    created_by,
    created_at,
    updated_at
)
SELECT
    UUID(),
    @plan_id,
    c.id,
    ep.id,
    CONCAT(@seed_prefix, LPAD(s.n, 3, '0')),
    CONCAT('Seed Planned Activity ', s.n),
    IF(MOD(s.n, 2) = 0, 'Internal', 'External'),
    IF(MOD(s.n, 2) = 0, 'One shot', 'Successive performance'),
    CONCAT('Generated test planned activity #', s.n, ' for database validation.'),
    ELT((MOD(s.n - 1, 4) + 1), 'PARTNERSHIP', 'SPONSORSHIP', 'CHARITY_DONATION', 'OTHERS'),
    ELT((MOD(s.n - 1, 4) + 1), 'Monthly', 'Quarterly', 'Annual', 'One-time'),
    1000 + (s.n * 125),
    10 + s.n,
    ELT((MOD(s.n - 1, 4) + 1), 'people', 'trees', 'hours', 'kits'),
    ELT((MOD(s.n - 1, 3) + 1), '1 month', '6 months', '1 year'),
    5 + MOD(s.n, 25),
    @seed_year,
    1 + MOD(s.n - 1, 5),
    ELT((MOD(s.n - 1, 4) + 1), 'HR', 'Operations', 'QHSE', 'CSR Team'),
    'DRAFT',
    @user_id,
    NOW(),
    NOW()
FROM tmp_seq_planned s
JOIN tmp_categories c
  ON c.rn = MOD(s.n - 1, @category_count) + 1
LEFT JOIN tmp_partner_names tpn
  ON tpn.n = s.n
LEFT JOIN external_partners ep
  ON ep.name COLLATE utf8mb4_unicode_ci = tpn.partner_name COLLATE utf8mb4_unicode_ci;

DROP TEMPORARY TABLE IF EXISTS tmp_generated_activities;
CREATE TEMPORARY TABLE tmp_generated_activities AS
SELECT
    id,
    ROW_NUMBER() OVER (ORDER BY activity_number) AS rn
FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

INSERT INTO csr_objectives (
    id,
    activity_id,
    objective,
    created_at
)
SELECT
    UUID(),
    ga.id,
    CONCAT('Announced objective ', obj.obj_no, ' for activity ', LPAD(ga.rn, 3, '0')),
    NOW()
FROM tmp_generated_activities ga
JOIN (
    SELECT 1 AS obj_no
    UNION ALL
    SELECT 2
) obj;

INSERT INTO csr_completed_objectives (
    id,
    activity_id,
    objective,
    achieved,
    created_at
)
SELECT
    UUID(),
    ga.id,
    CONCAT('Completed objective 1 for activity ', LPAD(ga.rn, 3, '0')),
    TRUE,
    NOW()
FROM tmp_generated_activities ga;

DROP TEMPORARY TABLE IF EXISTS tmp_seq_realized;
CREATE TEMPORARY TABLE tmp_seq_realized (
    n INT PRIMARY KEY
);

INSERT INTO tmp_seq_realized (n)
WITH RECURSIVE seq AS (
    SELECT 1 AS n
    UNION ALL
    SELECT n + 1
    FROM seq
    WHERE n < @realized_count
)
SELECT n
FROM seq;

INSERT INTO realized_activity (
    id,
    activity_id,
    participants,
    corporate_image_improved,
    incidents_number,
    contact_department,
    realized_budget,
    action_impact_actual,
    action_impact_unit,
    is_off_plan,
    off_plan_validation_mode,
    off_plan_validation_step,
    realization_date,
    comment,
    contact_name,
    contact_email,
    created_by,
    created_at,
    updated_at,
    status
)
SELECT
    UUID(),
    ga.id,
    8 + MOD(sr.n, 40),
    IF(MOD(sr.n, 5) = 0, FALSE, TRUE),
    MOD(sr.n, 4),
    ELT((MOD(sr.n - 1, 4) + 1), 'HR', 'Operations', 'QHSE', 'CSR Team'),
    700 + (sr.n * 45),
    5 + sr.n,
    ELT((MOD(sr.n - 1, 4) + 1), 'people', 'trees', 'hours', 'kits'),
    FALSE,
    NULL,
    NULL,
    DATE_ADD(MAKEDATE(@seed_year, 1), INTERVAL MOD(sr.n * 7, 330) DAY),
    CONCAT('Generated test realization #', sr.n),
    CONCAT('Seed Contact ', sr.n),
    CONCAT('seed+', sr.n, '@example.com'),
    @user_id,
    NOW(),
    NOW(),
    'DRAFT'
FROM tmp_seq_realized sr
JOIN tmp_generated_activities ga
  ON ga.rn = MOD(sr.n - 1, @planned_count) + 1;

UPDATE csr_plans
SET status = 'VALIDATED',
    validated_at = NOW(),
    validation_step = NULL,
    updated_at = NOW()
WHERE id = @plan_id;

UPDATE planned_activity
SET status = 'VALIDATED',
    updated_at = NOW()
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

UPDATE realized_activity ra
INNER JOIN planned_activity pa
  ON pa.id = ra.activity_id
SET ra.status = 'VALIDATED',
    ra.updated_at = NOW()
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;

INSERT INTO activity_kpis (
    id,
    plan_id,
    activity_id,
    incidents_count,
    participants_actual_sum,
    employees_planned,
    involvement_rate,
    announced_objectives_count,
    completed_objectives_count,
    action_delivery_rate,
    realized_budget_sum,
    planned_budget_amount,
    budget_control_rate,
    plan_total_hc,
    participants_vs_total_hc_rate,
    lifecycle_status,
    created_at,
    updated_at
)
SELECT
    UUID(),
    pa.plan_id,
    pa.id,
    COALESCE(SUM(ra.incidents_number), 0) AS incidents_count,
    COALESCE(SUM(ra.participants), 0) AS participants_actual_sum,
    pa.employees_planned,
    CASE
        WHEN COALESCE(pa.employees_planned, 0) = 0 THEN NULL
        ELSE ROUND((COALESCE(SUM(ra.participants), 0) / pa.employees_planned) * 100, 2)
    END AS involvement_rate,
    COALESCE(obj.announced_count, 0) AS announced_objectives_count,
    COALESCE(cobj.completed_count, 0) AS completed_objectives_count,
    CASE
        WHEN COALESCE(obj.announced_count, 0) = 0 THEN NULL
        ELSE ROUND((COALESCE(cobj.completed_count, 0) / obj.announced_count) * 100, 2)
    END AS action_delivery_rate,
    COALESCE(SUM(ra.realized_budget), 0) AS realized_budget_sum,
    pa.planned_budget AS planned_budget_amount,
    CASE
        WHEN COALESCE(pa.planned_budget, 0) = 0 THEN NULL
        ELSE ROUND((COALESCE(SUM(ra.realized_budget), 0) / pa.planned_budget) * 100, 2)
    END AS budget_control_rate,
    cp.total_hc AS plan_total_hc,
    CASE
        WHEN COALESCE(cp.total_hc, 0) = 0 THEN NULL
        ELSE ROUND((COALESCE(SUM(ra.participants), 0) / cp.total_hc) * 100, 2)
    END AS participants_vs_total_hc_rate,
    CASE
        WHEN cp.status = 'DRAFT' THEN 'DRAFT'
        WHEN cp.status IN ('VALIDATED', 'LOCKED') THEN
            CASE
                WHEN COUNT(ra.id) > 0 THEN 'COMPLETED'
                WHEN cp.year < YEAR(CURDATE()) THEN 'COMPLETED'
                WHEN cp.year = YEAR(CURDATE()) THEN 'PENDING'
                ELSE 'PLANNED'
            END
        WHEN pa.status = 'DRAFT' THEN 'DRAFT'
        WHEN SUM(CASE WHEN COALESCE(ra.status, 'DRAFT') <> 'DRAFT' THEN 1 ELSE 0 END) > 0 THEN 'COMPLETED'
        WHEN COUNT(ra.id) > 0 THEN 'DRAFT'
        WHEN cp.year IS NOT NULL AND cp.year >= YEAR(CURDATE()) THEN 'PENDING'
        ELSE 'PLANNED'
    END AS lifecycle_status,
    NOW(),
    NOW()
FROM planned_activity pa
JOIN csr_plans cp ON cp.id = pa.plan_id
LEFT JOIN realized_activity ra ON ra.activity_id = pa.id
LEFT JOIN (
    SELECT activity_id, COUNT(*) AS announced_count
    FROM csr_objectives
    GROUP BY activity_id
) obj ON obj.activity_id = pa.id
LEFT JOIN (
    SELECT activity_id, COUNT(*) AS completed_count
    FROM csr_completed_objectives
    WHERE achieved = TRUE
    GROUP BY activity_id
) cobj ON cobj.activity_id = pa.id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern
GROUP BY
    pa.plan_id,
    pa.id,
    pa.employees_planned,
    pa.planned_budget,
    cp.total_hc,
    obj.announced_count,
    cobj.completed_count;

COMMIT;

SELECT 'seed_test_activities.sql completed' AS message;
SELECT @site_id AS site_id, @plan_id AS plan_id, @seed_year AS plan_year;
SELECT COUNT(*) AS planned_seeded
FROM planned_activity
WHERE plan_id = @plan_id
  AND activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;
SELECT COUNT(*) AS realized_seeded
FROM realized_activity ra
JOIN planned_activity pa ON pa.id = ra.activity_id
WHERE pa.plan_id = @plan_id
  AND pa.activity_number COLLATE utf8mb4_unicode_ci LIKE @seed_pattern;
